name: Put my code on PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-put:
    name: Build the package and send to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get Python ready
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install the builder tool
      run: >-
        python -m
        pip install
        build
        --user
    - name: Make the files for distribution
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        - name: Send everything to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_TOKEN }}
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v2
          with:
            generate_release_notes: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    